name: clover_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: "^0.2.7"

  cupertino_icons: ^0.1.2

  #sameers
  http: ^0.12.0

  #camera: ^0.2.3
  camera:
    git:
      url: git://github.com/kmorkos/plugins.git
      ref: camera/crash-fix
      path: packages/camera/
  path_provider: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - lib/assets/images/logoFull.png
   - lib/assets/images/treeImg/1.png
   - lib/assets/images/treeImg/2.png
   - lib/assets/images/treeImg/3.png
   - lib/assets/images/treeImg/4.png
   - lib/assets/images/treeImg/5.png
   - lib/assets/images/treeImg/6.png
   - lib/assets/images/treeImg/7.png
   - lib/assets/images/treeImg/8.png
   - lib/assets/images/treeImg/9.png
   - lib/assets/images/treeImg/10.png

  fonts:
    - family: Quicksand
      fonts:
        - asset: lib/assets/fonts/Quicksand/Quicksand-Regular.ttf
  